/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "/s": "/秒",
    "Clear": "清除",
    "Compact fully upgraded": "紧凑型全面升级",
    "Crafting": "制作",
    "Foundries": "铸造厂",
    "Mana": "法力",
    "Generation": "生成",
    "Sort": "排序",
    "Speed": "速度",
    "Yield": "生产",
    "• No bonuses": "• 无加成",
    "Base time:": "基础时间:",
    "crafting T": "制作 T",
    "Effective:": "效率:",
    "foundry": "铸造厂",
    "Gem": "宝石",
    "Gems": "宝石",
    "Idle": "空闲",
    "Impact (": "影响 (",
    "mana to unlock": "法力去解锁",
    "Prisms": "棱镜",
    "Select Recipe": "选择配方",
    "Requires": "要求",
    "Speed: ×": "速度: ×",
    "Stop Production": "停止生产",
    "Upgrade": "升级",
    "Yield: ×": "生产: ×",
    "Tip: right click to set recipe for all slots. Right clicking on a crafting slot clears it.": "提示：右键单击可以设置所有槽的配方。右键点击一个制作槽可以清除它。",
    "Community": "社区",
    "Copy to Clipboard": "复制到剪贴板",
    "Danger Zone": "危险区",
    "Display Settings": "显示设置",
    "Export Save": "导出存档",
    "Download File": "下载文件",
    "Hard Reset": "硬重置",
    "Import Save": "导入存档",
    "Imported from file": "已导入文件",
    "Join Discord": "加入 Discord",
    "Load File": "从文件导入",
    "Numbers above this value will display in scientific notation.": "高于此值的数字将以科学记数法显示。",
    "Paste from Clipboard": "从剪切板粘贴",
    "Preview:": "预览:",
    "Scientific Notation Threshold": "科学记数法阈值",
    "This will permanently delete all progress.": "这将永久删除所有进度。",
    "Artifacts": "神器",
    "• Prisms: ×": "• 棱镜: ×",
    "• Speed: ×": "• 速度: ×",
    "• Upgrades: ×": "• 升级: ×",
    "• Yield: ×": "• 生产: ×",
    "Affects: T": "影响: T",
    "Basic Prism": "基础棱镜",
    "chunks": "块",
    "Cost per chunk:": "成本每块:",
    "Cost:": "成本:",
    "deficit will increase": "赤字将会增加",
    "foundries": "铸造厂",
    "gems": "宝石",
    "Hide crafted": "隐藏已制作",
    "Progress:": "进度:",
    "When complete:": "当完成:",
    "Attack": "攻击",
    "No foundries crafting T": "没有铸造厂在制造 T",
    "Attack Speed": "攻击速度",
    "Combat": "战斗",
    "Combat Upgrades": "战斗升级",
    "Core Upgrades": "核心升级",
    "Energy Cores": "能量核心",
    "Damage": "伤害",
    "Damage:": "伤害:",
    "Enemy #": "敌人 #",
    "Crafting Slot": "制作槽位",
    "Energy Cores": "能量核心",
    "Faster Revive": "更快的复活",
    "Health": "生命值",
    "HP": "生命值",
    "Highest Enemy": "敌人最高记录",
    "Mana Boost": "法力提升",
    "Speed:": "速度:",
    "VS": "VS",
    "You": "你",
    "Craft Speed": "制作速度",
    "Core Upgrades": "核心升级",
    "DEFEATED": "被击败了",
    "Reviving in...": "复活中...",
    "• Global: ×": "• 全局: ×",
    "Combat Artifacts": "战斗神器",
    "attack speed": "攻击速度",
    "Cost per cycle:": "每循环成本:",
    "cycles": "循环",
    "HP/s regen": "生命值/秒 回复",
    "max HP": "最大生命值",
    "Combat bonuses:": "战斗加成:",
    "HP/s": "生命值/秒",
    "speed": "速度",
    "Exported to clipboard": "已导出到剪贴板",
    "MAX": "满级",
    "Pulverizer": "粉碎机",
    "(CAPPED)": "(上限)",
    "Auto Combat": "自动战斗",
    "Current Mana": "当前法力",
    "Base SP": "基础奇点点数",
    "Next Milestone": "下一个里程碑",
    "Hide completed": "隐藏已完成",
    "Singularity Points": "奇点点数",
    "SP": "奇点点数",
    "SP Calculation": "奇点点数计算",
    "Skill Tree": "技能树",
    "Singularity": "奇点",
    "Singularities": "奇点",
    "Total": "总计",
    "Unlock Mastery": "解锁精通",
    "Unlocks the Mastery system": "解锁精通系统",
    "What Persists": "什么会持续存在",
    "What Resets": "什么会重置",
    "Perform Singularity": "执行奇点",
    "• All gem upgrades (Speed/Yield)": "• 所有宝石升级（速度/产量）",
    "• All skill tree purchases": "• 所有技能树购买",
    "• Artifacts (except kept by Artifact Memory)": "• 神器（被神器记忆保存的除外）",
    "• Combat progress and upgrades": "• 战斗进度和升级",
    "• Foundry count (resets to 1 + extra slots)": "• 铸造厂数量（重置为 1 + 额外槽位）",
    "• Mana and all gems": "• 法力和所有宝石",
    "• Mastery (shards and levels)": "• 精通（碎片和等级）",
    "• Milestone unlocks": "• 里程碑解锁",
    "• Prisms (except kept by Prism Memory)": "• 棱镜（棱镜存储器保存除外）",
    "• Singularity Points (SP)": "• 奇点点数（SP）",
    "• Tab unlocks": "• 选项卡解锁",
    "Auto-unlock & upgrades": "自动解锁和升级",
    "Automatically buys Speed and Yield upgrades for T1 and T2 gems when you can afford them, without spending mana.": "自动购买速度和产量升级T1和T2宝石时，你可以负担得起他们，不消耗法力。",
    "Automatically buys Speed and Yield upgrades for T3 and T4 gems when you can afford them, without spending mana.": "自动购买速度和产量升级T3和T4宝石时，你可以负担得起，不消耗法力。",
    "Automatically unlocks combat (spends 20T mana) and auto-buys combat upgrades (HP, Damage, Attack Speed, Revive Speed) when you can afford them, without spending mana.": "自动解锁战斗（花费20T法力值）和自动购买战斗升级（HP，伤害，攻速，复活速度），当你能负担的时候，不消耗法力值。",
    "Mastery lets you collect shards from gem crafting to gain permanent bonuses.": "精通可以让你从宝石制作中收集碎片来获得永久奖励。",
    "more for": "更多关于",
    "Perform your first singularity to unlock": "执行你的第一个奇点来解锁",
    "Perform your first singularity to unlock the skill tree.": "执行你的第一个奇点来解锁技能树。",
    "(You have": "(你有",
    "Next:": "下一个:",
    "Mastery": "精通",
    "damage": "伤害",
    "Current:": "当前:",
    "Combat Mastery": "战斗精通",
    "Level:": "等级:",
    "mana": "法力",
    "Mana is no longer capped at 1e27. Gain more SP per singularity based on how far past the cap you go.": "法力不再上限为1e27。每个奇点获得更多的奇点点数取决于你超过上限的距离。",
    "Prism Memory": "棱镜存储",
    "Prism Power": "棱镜力量",
    "Remove 1e27 mana cap": "移除 1e27 法力上限",
    "Speed Boost (free)": "速度提升 (免费)",
    "✓ Maxed": "✓ 最大",
    "Gem Mastery": "宝石精通",
    "Keep highest tier artifact per level": "每级保留最高层级的神器",
    "Keep highest tier prism per level": "每级保留最高层级的棱镜",
    "Foundry Expansion": "铸造厂扩建",
    "Artifact Memory": "神器存储",
    "Break Singularity": "打破奇点",
    "Click nodes adjacent to owned nodes to purchase. Drag to pan. All bonuses persist through resets.": "点击与已拥有节点相邻的节点进行购买。拖动以移动。所有的奖励通过重置持续存在。",
    "+0.1x prism effectiveness per level (additive)": "每级+0.1x棱镜效率（加法）",
    "+1 starting foundry slot per level": "每级+1铸造厂槽位",
    "+2 max level for gem speed/yield upgrades per level": "每级+2宝石速度/产量升级等级上限",
    "| Chance:": "| 几率:",
    "| Rolls:": "| 重掷:",
    "% speed, +": "% 速度, +",
    "% yield": "% 产量",
    "Current: +": "当前: +",
    "Energy Core Drops": "能量核心掉落",
    "From": "从",
    "Level": "等级",
    "Level Bonus": "等级加成",
    "Shard Log": "碎片日志",
    "Character Locked": "角色未解锁",
    "Unlock Combat": "解锁战斗",
    "Global Yield": "全局生产",
    "Global Speed": "全局速度",
    "How It Works": "工作原理",
    "Artifact Effectiveness": "神器效果",
    "Shards": "碎片",
    "shards = level up": "碎片 = 升级",
    "Speed Bonus": "速度加成",
    "Total:": "总计:",
    "Yield Bonus": "生产加成",
    "Mastery Bonuses": "精通加成",
    "per craft": "每次制作",
    "No shards found yet...": "暂未发现碎片...",
    "Prism Effectiveness": "棱镜效果",
    "• Each shard: +": "• 每个碎片: +",
    "• Each tier has a unique level bonus": "• 每层都有一个独特的等级奖励",
    "• Mastery persists through resets": "• 精通通过重置持续存在",
    "• Each gem craft has a chance to drop a shard": "• 每个宝石制作有几率掉落一个碎片",
    "• Drop rate scales with level (see tier cards)": "• 掉落率随等级变化（参见层级卡片）",
    "chance)": "几率)",
    "Combat Veteran": "战斗老兵",
    "Bonus Cores": "奖励核心",
    "Mana Bonus (": "法力加成 (",
    "Merge": "合并",
    "rolls": "重掷之后",
    "SP Boost": "奇点点数提升",
    "will go negative!": "将会变成负数！",
    "Merge Grid Size": "合并网格大小",
    "Ascension": "转生",
    "after": "在",
    "+0.5x energy core drops per level (additive)": "每级+0.5x能量核心掉落（添加）",
    "+1 max level for combat mana upgrades per level": "每级+1战斗法力升级上限",
    "+1 merge grid row and column per level": "每级+1合并网格行和列",
    "+5 combat upgrade caps": "+5战斗升级上限",
    "+50% SP gain": "+50% 奇点点数增益",
    "All singularity point gains are increased by 50%.": "所有奇点点数增益增加50%。",
    "Raises maximum level for HP, Damage, and Attack Speed by 5. Revive Speed caps at 15 (instant revive).": "提高生命值，攻击力和攻速的最高等级5。恢复速度上限为15（即时恢复）。",
    "Spawn Log": "生成日志",
    "Prism": "棱镜",
    "No gems spawned yet": "暂无已生成宝石",
    "Merge Bonuses": "合并加成",
    "Lv": "等级",
    "Delete Gem": "删除宝石",
    "Grid persists through Singularity. Gem cost resets.": "网格通过奇点持续存在。宝石成本重置。",
    "Delete Gem": "删除宝石",
    "Buy Random Gem": "购买随机宝石",
    "Buy random gems to fill the grid. Identical gems auto-merge into higher levels.": "购买随机宝石来填满格子。相同的宝石自动合并到更高的等级。",
    "Confirm Delete": "确认删除",
    "Click a gem to delete": "点击一个宝石以删除",
    "Required:": "要求:",
    "to Universe": "到宇宙",
    "Universe": "宇宙",
    "You may": "你可以",
    "features are coming soon...": "功能即将推出...",
    "Current Mana:": "当前法力:",
    "Ascend": "转生",
    ", discovering new challenges and features beyond this reality.": "发现超越现实的新挑战和新特征。",
    "Ascending now will prepare your save for future content.": "现在转生将为将来的内容准备你的保存。",
    "Warning: Ascending will reset ALL progress. Your gems, foundries, upgrades, prisms, combat, singularity, mastery, and merge progress will be lost.": "警告：转生将重置所有进度。你的宝石、铸造厂、升级、棱镜、战斗、奇点、精通和合并进程将会丢失。",
    "You have reached the pinnacle of Universe": "你已经到达了宇宙的巅峰",
    "Dust": "魔尘",
    "Enchanting": "附魔",
    "Pulverizers": "粉碎机",
    "Cost per craft:": "每次制作成本:",
    "Produces:": "生产:",
    "Select Pulverizer Recipe": "选择粉碎配方",
    "applied": "已应用",
    "Current": "当前",
    "Discount": "折扣",
    "Enchant": "附魔",
    "enchantment": "附魔",
    "Enchanting cost:": "附魔成本:",
    "Next": "下一级",
    "Strength": "力量",
    "Tier": "层级",
    "Select gem tier to enchant": "选择要附魔的宝石层级",
    "Reduces the gem cost to craft this tier. Shows cost as % of original.": "减少制造这个层级所需的宝石。显示成本为原价的%。",
    "Increases the mana bonus provided by this gem tier.": "增加这个宝石层级提供的法力加成。",
    "Increases crafting speed for this gem tier.": "提升本层级宝石的制造速度。",
    "Swift Crafting": "快速制作",
    "Reset": "重置",
    "All crafting speed is doubled.": "所有制造速度加倍。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "×": "×",
    "=": "=",
    "▶": "▶",
    "—": "—",
    "🔒 ???": "🔒 ???",
    "→": "→",
    "⚠ T": "⚠ T",
    "✓": "✓",
    "• +": "• +",
    "• ×": "• ×",
    "○": "○",
    "🔒": "🔒",
    "•": "•",
    "%": "%",
    "^": "^",
    "→ x": "→ x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': '',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "• Base drop rate: ": "• 基础掉率: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " mana": " 法力",
    " cores": " 核心",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(([\d\.]+)m\)$/,
    /^\(([\d\.]+)k\)$/,
    /^\-([\d\.]+)k\/s$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)t$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^\(([\d\.]+)k\)$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+)qa$/,
    /^([\d\.]+)qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+), T([\d\.,]+)$/,
    /^([\d\.,]+), T([\d\.,]+), T([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^Generates ([\d\.]+) mana\/sec$/, '生产 $1 法力/秒'],
    [/^All scale ([\d\.]+)x per level$/, '所有比例为每级 $1x'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x craft speed$/, '$1x 制作速度'],
    [/^([\d\.]+)x global crafting speed$/, '$1x 全局制作速度'],
    [/^([\d\.]+)x T([\d\.]+) speed, ([\d\.]+)x yield per level$/, '$1x T$2 速度, $3x 产量每级'],
    [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed$/, '$1 生命值/秒 回复, $2x 生命值, $3x 攻击速度'],
    [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed, ([\d\.]+)x damage$/, '$1 生命值/秒 回复, $2x 生命值, $3x 攻击速度, $4x 伤害'],
    [/^×([\d\.]+) global \(([\d\.]+)x\)$/, '×$1 全局 ($2x)'],
    [/^×([\d\.]+) HP \(([\d\.]+)x\)$/, '×$1 生命值 ($2x)'],
    [/^×([\d\.]+) Damage \(([\d\.]+)x\)$/, '×$1 伤害 ($2x)'],
    [/^×([\d\.]+) Speed \(([\d\.]+)x\)$/, '×$1 速度 ($2x)'],
    [/^×([\d\.]+) mana \(([\d\.]+)x\)$/, '×$1 法力 ($2x)'],
    [/^([\d\.]+)x speed, ([\d\.]+)x yield for T([\d\.]+)\-T([\d\.]+)$/, '$1x 速度, $2x 生产 对于 T$3-T$4'],
    [/^\+([\d\.]+) slot \(\+([\d\.]+) total\)$/, '+$1 槽位 (+$2 总计)'],
    [/^\-([\d\.]+)s revive \(([\d\.]+)s\)$/, '-$1 秒 复活 ($2秒)'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% global speed per level$/, '每级 +$1% 全局速度'],
    [/^\+([\d\.]+)\% global yield per level$/, '每级 +$1% 全局生产'],
    [/^\+([\d\.]+)\% energy core drops per level$/, '每级 +$1% 能量和谐掉落'],
    [/^\+([\d\.]+)\% prism effectiveness per level$/, '每级 +$1% 棱镜效果'],
    [/^\+([\d\.]+)\% artifact effectiveness per level$/, '每级 +$1% 神器效果'],
    [/^\+([\d\.]+)\% singularity points per level$/, '每级 +$1% 奇点点数'],
    [/^\+([\d\.]+)\% base$/, '+$1% 基础'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)\% to Ascension$/, '$1% 转生进度'],
    [/^\+([\d\.]+)\% mana multiplier$/, '+$1% 法力乘数'],
    [/^\+([\d\.]+)\/s$/, '+$1/秒'],
    [/^\+([\d\.]+)\/hr$/, '+$1/小时'],
    [/^\-([\d\.]+)\/hr$/, '-$1/小时'],
    [/^\-([\d\.]+)\/s$/, '-$1/秒'],
    [/^([\d\.]+)k\/s$/, '$1k/秒'],
    [/^\+([\d\.]+)k\/s$/, '+$1k/秒'],
    [/^\-([\d\.]+)k\/s$/, '-$1k/秒'],
    [/^\-([\d\.]+)m\/s$/, '-$1m/秒'],
    [/^\-([\d\.]+)b\/s$/, '-$1b/秒'],
    [/^\+([\d\.]+)\/min$/, '+$1/分钟'],
    [/^\-([\d\.]+)\/min$/, '-$1/分钟'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) tiers$/, '$1 层级'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^T([\d\.,]+) Shield$/, 'T$1 盾牌'],
    [/^T([\d\.,]+)-T([\d\.,]+) Automation$/, 'T$1-T$2 自动化'],
    [/^Automatically buys Speed and Yield upgrades for T([\d\.,]+) and T([\d\.,]+) gems when you can afford them, without spending mana.$/, '在你买得起的情况下，自动为T$1和T$2宝石购买速度和产量升级，而不需要消耗法力值。'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Lv.([\d\.,]+)$/, '等级 $1'],
    [/^T([\d\.,]+) Mastery: \+$/, 'T$1 精通: +'],
    [/^T([\d\.,]+) Lv([\d\.,]+)$/, 'T$1 等级 $2'],
    [/^T([\d\.,]+) Mastery \(Lv$/, 'T$1 (等级'],
    [/^T([\d\.,]+) Prism$/, 'T$1 棱镜'],
    [/^T([\d\.,]+) Mastery$/, 'T$1 精通'],
    [/^Crush T([\d\.,]+) Gem$/, '粉碎 T$1 宝石'],
    [/^Crush T([\d\.,]+) gems into T([\d\.,]+) dust$/, '粉碎 T$1 宝石 为 T$2 魔尘'],
    [/^Auto-buy T([\d\.,]+) \& T([\d\.,]+) upgrades \(free\)$/, '自动购买 T$1 和 T$2 升级（免费）'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);